"""empty message

Revision ID: 054e76fc2004
Revises: 296959b19624
Create Date: 2024-01-26 11:29:39.579423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '054e76fc2004'
down_revision = '296959b19624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.alter_column('Categories',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.alter_column('Categories',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
