"""empty message

Revision ID: 296959b19624
Revises: d81ac694d41d
Create Date: 2024-01-26 10:05:20.952918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296959b19624'
down_revision = 'd81ac694d41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
