"""add_the_appontement_tabels

Revision ID: 4adfe629507d
Revises: 720e4de1cc2b
Create Date: 2024-01-27 11:59:56.192942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4adfe629507d'
down_revision = '720e4de1cc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Lawyer_Schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lawyer_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('is_disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['Days.id'], ),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['Times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Appointements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['Lawyer_Schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Appointements')
    op.drop_table('Lawyer_Schedule')
    op.drop_table('Times')
    op.drop_table('Days')
    # ### end Alembic commands ###
