"""empty message

Revision ID: 720e4de1cc2b
Revises: 054e76fc2004
Create Date: 2024-01-26 11:32:01.130079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720e4de1cc2b'
down_revision = '054e76fc2004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.drop_index('phoneNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyers', schema=None) as batch_op:
        batch_op.create_index('phoneNumber', ['phoneNumber'], unique=True)

    # ### end Alembic commands ###
